# Site settings
title: Emily McAfee
description: > # this means to ignore newlines until "baseurl:" In November 2014, I began a 12-week program in web development at General Assembly in Washington, DC. I’m using this blog to chronicle my learning process, which may include: topics of intrigue, weird challenges, project aspirations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://emilymcafee.github.io" # the base hostname & protocol for your site
twitter_username: emilymcafee
github_username:  emilymcafee

# Build settings
markdown: kramdown
